name: Notifier Nilai ITS (Discord)

# 1. Trigger: setiap 15 menit + manual dispatch
on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      # 2. Checkout kode
      - uses: actions/checkout@v4

      # 3. Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 4. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 5. Run skrip
      - name: Run nilai.py
        env:
          COOKIE_NILAI:    ${{ secrets.COOKIE_NILAI }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: python nilai.py
